### ISSUE TITLE
提交Flask基本目录结构

### ISSUE THREAD

**Issue by BowenChenbm** [LouPlus/jobplus4-16#13]
提交Flask基本目录结构

**Comment by victorhuang1** [comment]
Mission complete.

至少要创建以下文件：

jobplus4-16/manage.py
jobplus4-16/requirements.txt 包含所有依赖的包，至少需要写入 flask flask-sqlalchemy mysqlclient flask-migrate flask-wtf flask-login 这些包，团队成员可以使用 pip install -r requirements.txt 来安装所有依赖的包。
jobplus4-16/jobplus/__init__.py
jobplus4-16/jobplus/app.py
jobplus4-16/jobplus/config.py
jobplus4-16/jobplus/decorators.py
jobplus4-16/jobplus/forms.py
jobplus4-16/jobplus/models.py
jobplus4-16/jobplus/templates/base.html
jobplus4-16/jobplus/handlers/front.py
